services:
  # --- SQL Server ---
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks: 
        - trilha-net-azure-desafio-network

  # --- Azurite (Blob + Queue + Table) ---
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - azurite_data:/data
    networks: 
        - trilha-net-azure-desafio-network

  # --- API .NET ---
  trilha-net-azure-desafio:
    image: trilhanetazuredesafio
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
      - azurite
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__SqlServer: "Server=sqlserver,1433;Database=Agendamento;User Id=sa;Password=Your_password123;"
      ConnectionStrings__AzureTableStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://azurite:10002/devstoreaccount1;"
    networks: 
        - trilha-net-azure-desafio-network

volumes:
  sql_data:
  azurite_data:

networks: 
  trilha-net-azure-desafio-network:
    driver: bridge
